# Generated by Django 2.2.16 on 2021-12-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211218_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, error_messages={'unique': 'IMAGE NOT UPLOADED'}, null=True, upload_to='posts/'),
        ),
    ]
